# accelerate_config.yaml
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
num_processes: 2           # Number of GPUs
fp16_backend: "native"
mixed_precision: bf16
use_deepspeed: true
deepspeed_config: "./ds_config.json"