compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
deepspeed_config:
  deepspeed_config_file: ds_config.json
machine_rank: 0
main_training_function: main
num_machines: 1
num_processes: 2
use_cpu: false
